# Generated by Django 4.2.1 on 2023-06-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='ImagenesProductos',
        ),
    ]
