# Generated by Django 4.2.1 on 2023-06-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_productos_imagenesproductos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
    ]
