# Generated by Django 4.2.1 on 2023-06-17 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_venta_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEnvio',
            fields=[
                ('id_tp_envio', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 15, 38, 37, 216223)),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoenvio')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='envio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.envio'),
        ),
    ]
